import Head from 'next/head'
import styles from '@/styles/Home.module.scss'
import { useEffect, useState } from 'react'

export default function Home() {
  const [projectName, setProjectName] = useState('')

  const getProjectName = async () => {
    try {
      const res = await fetch('/api/getProjectName')
      const data = await res.json()
      setProjectName(data.name)
    } catch (err) {
      console.log(err)
    }
  }

  useEffect(() => {
    getProjectName()
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>

        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <p className="font-bold underline text-4xl text-red-800	">
            {projectName}
          </p>
        </div>
      </main>
    </>
  )
}
